version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    environment:
      - FLASK_ENV=development